apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: dev
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - name: MYAPP
    protocol: TCP
    port: 80
    targetPort: 80
 